### ISSUE TITLE
自动同步(或是手动)"osu!\collection.db"，

### ISSUE THREAD

**Issue by MinecraftDeadBush** [Milkitic/Osu-Player#18]
没看懂收藏夹保存在哪里，
想的是，像"addons\workshop"一样
> 自动同步的收藏夹放在单独文件夹 即"workshop"文件夹
> 手动创建的收藏夹放在这一层外面 即"addons"文件夹

做一个"collection\osu!"文件夹

**Comment by Milkitic** [comment]
考虑 2.2 版本加入

**Comment by Milkitic** [comment]
db文件的存是hash，考虑到各种兼容问题就先不实现了
