### ISSUE TITLE
不能导入曲包

### ISSUE THREAD

**Issue by poly000** [Milkitic/Osu-Player#34]
版本：2.1.7255.104
注：我之前在D:\Download目录下安装了osu!，后手动移动到%APPDATA%\..\Local\osu!
选择%APPDATA%\..\Local\osu!\osu!.db后不能导入
OS: Windows10 1703

**Comment by Milkitic** [comment]
具体的症状是？选完后没有反应么

**Comment by sinsong** [comment]
我也是选了osu!.db后没有导入曲库，难道db变了？
