### ISSUE TITLE
error while loading 714239

### ISSUE THREAD

**Issue by Kyrios0** [Milkitic/Osu-Player#49]
- Issue
  There's an extra space after the `folder` while loading, which can cause error.

- Sample & Reproducible
  [714239](https://osu.ppy.sh/beatmapsets/714239): Yes
  [153887](https://osu.ppy.sh/beatmapsets/153887): Maybe

**Comment by Milkitic** [comment]
Tested: 
![image](https://user-images.githubusercontent.com/24785749/96331529-8ce3b380-1090-11eb-91e0-eadd82cd23cd.png)
![image](https://user-images.githubusercontent.com/24785749/96331940-d7b2fa80-1093-11eb-8718-8d727b3f529e.png)

I think it's a limit of .NET API. The `DirectoryInfo` Itself auto trimmed the path for both `Name` property and `FullName` property. While scanning beatmaps, I mostly used `DirectoryInfo` class:
https://github.com/Milkitic/Osu-Player/blob/master/OsuPlayer.Common/Scanning/OsuFileScanner.cs#L124
So fixing this line will resolve the problem I think.

**Comment by Kyrios0** [comment]
Let me explain this in detail:
After I pressing the 'Play' buttom, OsuPlayer starts to load 714239. Here's the snapshot of `folder` where found a extra space.
![图片](https://user-images.githubusercontent.com/25918984/96335613-895e2580-10ac-11eb-8e99-0a7d0bacfc4e.png)

But actually, open a powershell in this folder, I found there should be no space at the end of `folder`.
![图片](https://user-images.githubusercontent.com/25918984/96335675-db06b000-10ac-11eb-9386-104e386be88f.png)

So the error is: When the player is trying to load resources from `folder`, the `StreamRead` function will raise `System.IO.DirectoryNotFoundException` because `folder + ' \\' + resource` is not exist.

**Comment by Kyrios0** [comment]
Here's `Folder name` in `osu!db`
![图片](https://user-images.githubusercontent.com/25918984/96337110-127a5a00-10b7-11eb-8acb-c86ad736c7d6.png)

**Comment by Milkitic** [comment]
OK it's a bug of osu db. Tried to optimize it

**Comment by Milkitic** [comment]
Closed
