### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by Kashouryo** [Milkitic/Osu-Player#7]
This source code is extremely broken and unable to build on other computers.

`严重性	代码	说明	项目	文件	行	禁止显示状态
错误		XML 命名空间“clr-namespace:Loaders;assembly=MrMitch.Loaders”中不存在标记“ChromeLoader”。 行 693 位置 18.	OsuPlayer.Wpf	C:\GitHub\Osu-Player\OsuPlayer.Wpf\Windows\MainWindow.xaml	693	
错误		XML 命名空间“clr-namespace:Milky.OsuPlayer.Common.Metadata;assembly=OsuPlayer.Common”中不存在标记“BeatmapDataModel”。 行 103 位置 30.	OsuPlayer.Wpf	C:\GitHub\Osu-Player\OsuPlayer.Wpf\Pages\RecentPlayPage.xaml	103	
错误		XML 命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在标记“Arc”。 行 28 位置 30.	MrMitch.Loaders	C:\GitHub\Osu-Player\MrMitch.Loaders\Themes\Generic.xaml	28	
错误	CS1929	“IEnumerable<MapInfo>”不包含“ToBeatmapEntries”的定义，并且最佳扩展方法重载“EntryExtension.ToBeatmapEntries(IEnumerable<IMapIdentifiable>, IEnumerable<BeatmapEntry>, bool)”需要类型为“IEnumerable<IMapIdentifiable>”的接收器	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\EntryExtension.cs	118	活动的
错误	CS1929	“List<MapInfo>”不包含“ToBeatmapEntries”的定义，并且最佳扩展方法重载“EntryExtension.ToBeatmapEntries(IEnumerable<IMapIdentifiable>, IEnumerable<BeatmapEntry>, bool)”需要类型为“IEnumerable<IMapIdentifiable>”的接收器	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\BeatmapEntryQuery.cs	96	活动的
错误	XDG0008	命名空间“clr-namespace:Loaders;assembly=MrMitch.Loaders”中不存在“ChromeLoader”名称。	OsuPlayer.Wpf	MainWindow.xaml	693	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“IconMarginConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	33	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“LyricWindowLockedConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	37	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“LyricWindowShownConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	36	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“MiniEnabledConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	35	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“MsToStringConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	39	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“NavigationColorConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	76	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“NavigationWidthConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	32	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“TitleVisibleConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	34	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“VideoShowConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	38	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.ViewModels”中不存在“MainWindowViewModel”名称。	OsuPlayer.Wpf	MainWindow.xaml	29	
错误	CS0103	当前上下文中不存在名称“MetaString”	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\BeatmapEntryQuery.cs	105	活动的
错误	CS0103	当前上下文中不存在名称“MetaString”	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\BeatmapEntryQuery.cs	108	活动的
错误	XLS0503	无法将类型为“String”的值添加到类型为“InlineCollection”的集合或字典中。	OsuPlayer.Wpf	MainWindow.xaml	124	
错误	CS0016	未能写入输出文件“C:\Users\YureruMiira\Source\Repos\OSharp\OSharp\OSharp.xml”--“未能找到路径“C:\Users\YureruMiira\Source\Repos\OSharp\OSharp\OSharp.xml”的一部分。”	OSharp.Api	C:\GitHub\Osu-Player\OSharp.Api\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\GitHub\Osu-Player\OSharp.Api\bin\Debug\netstandard2.0\OSharp.Api.dll”	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\CSC	1	活动的
错误	CS0006	未能找到元数据文件“C:\GitHub\Osu-Player\OsuPlayer.Common\bin\Debug\OsuPlayer.Common.dll”	OsuPlayer.Media.Audio	C:\GitHub\Osu-Player\OsuPlayer.Media.Audio\CSC	1	活动的
错误	CS0246	未能找到类型或命名空间名“ConcurrentRandom”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\BeatmapEntryQuery.cs	12	活动的
错误	CS0246	未能找到类型或命名空间名“ConcurrentRandom”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\BeatmapEntryQuery.cs	12	活动的
错误	CS0246	未能找到类型或命名空间名“IMapIdentifiable”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\EF\Model\MapInfo.cs	9	活动的
错误	CS0246	未能找到类型或命名空间名“IMapIdentifiable”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\EntryExtension.cs	16	活动的
错误	CS0246	未能找到类型或命名空间名“IMapIdentifiable”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\EntryExtension.cs	22	活动的
错误	CS0246	未能找到类型或命名空间名“IMapIdentifiable”(是否缺少 using 指令或程序集引用?)	OsuPlayer.Common	C:\GitHub\Osu-Player\OsuPlayer.Common\Data\EntryExtension.cs	109	活动的
错误		类型引用无法找到名为“Arc”的公共类型。 行 21 位置 36.	MrMitch.Loaders	C:\GitHub\Osu-Player\MrMitch.Loaders\GooglePlusLoader.xaml	21	
`

Also, for osharp references, they are using absolute paths which do not work on other computers either.

Awesome software overall, nice job Milkitic!

**Comment by Milkitic** [comment]
Please try again to clone the whole repo including the submodules. Maybe it works now for the latest commit.

**Comment by Kashouryo** [comment]
unfortunately, I updated the source code but it still doesn't work
`严重性	代码	说明	项目	文件	行	禁止显示状态
错误		XML 命名空间“clr-namespace:Loaders;assembly=MrMitch.Loaders”中不存在标记“ChromeLoader”。 行 693 位置 18.	OsuPlayer.Wpf	C:\GitHub\Osu-Player\OsuPlayer.Wpf\Windows\MainWindow.xaml	693	
错误		一些 NuGet 程序包是使用不同于当前目标框架的目标框架安装的，可能需要重新安装。有关详细信息，请访问 http://docs.nuget.org/docs/workflows/reinstalling-packages。受到影响的程序包: System.ValueTuple	OsuPlayer.Wpf		0	
错误	XDG0008	命名空间“clr-namespace:Loaders.Converters”中不存在“LinearConverter”名称。	MrMitch.Loaders	Generic.xaml	114	
错误	XDG0008	命名空间“clr-namespace:Loaders.Converters”中不存在“LinearConverter”名称。	MrMitch.Loaders	Generic.xaml	115	
错误	XDG0008	命名空间“clr-namespace:Loaders.Converters”中不存在“LinearConverter”名称。	MrMitch.Loaders	Generic.xaml	116	
错误	XDG0008	命名空间“clr-namespace:Loaders.Converters”中不存在“LinearConverter”名称。	MrMitch.Loaders	Generic.xaml	117	
错误	XDG0008	命名空间“clr-namespace:Loaders.Converters”中不存在“LinearConverter”名称。	MrMitch.Loaders	Generic.xaml	118	
错误	XDG0008	命名空间“clr-namespace:Loaders;assembly=MrMitch.Loaders”中不存在“ChromeLoader”名称。	OsuPlayer.Wpf	MainWindow.xaml	693	
错误	XDG0008	命名空间“clr-namespace:Loaders”中不存在“ChromeLoader”名称。	MrMitch.Loaders	Generic.xaml	9	
错误	XDG0008	命名空间“clr-namespace:Loaders”中不存在“ChromeLoader”名称。	MrMitch.Loaders	Generic.xaml	19	
错误	XDG0008	命名空间“clr-namespace:Loaders”中不存在“ImgurLoader”名称。	MrMitch.Loaders	Generic.xaml	94	
错误	XDG0008	命名空间“clr-namespace:Loaders”中不存在“ImgurLoader”名称。	MrMitch.Loaders	Generic.xaml	101	
错误	XDG0008	命名空间“clr-namespace:Milky.OsuPlayer.Converter”中不存在“NavigationColorConverter”名称。	OsuPlayer.Wpf	MainWindow.xaml	76	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	103	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	127	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	133	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	139	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	145	
错误	XDG0008	命名空间“http://schemas.microsoft.com/expression/2010/drawing”中不存在“Arc”名称。	MrMitch.Loaders	Generic.xaml	151	
错误	XLS0414	未找到类型“ed:Arc”。请确保不缺少程序集引用并且已生成所有引用的程序集。	MrMitch.Loaders	Generic.xaml	127	
错误	XLS0414	未找到类型“ed:Arc”。请确保不缺少程序集引用并且已生成所有引用的程序集。	MrMitch.Loaders	Generic.xaml	133	
错误	XLS0414	未找到类型“ed:Arc”。请确保不缺少程序集引用并且已生成所有引用的程序集。	MrMitch.Loaders	Generic.xaml	139	
错误	XLS0414	未找到类型“ed:Arc”。请确保不缺少程序集引用并且已生成所有引用的程序集。	MrMitch.Loaders	Generic.xaml	145	
错误	XLS0414	未找到类型“ed:Arc”。请确保不缺少程序集引用并且已生成所有引用的程序集。	MrMitch.Loaders	Generic.xaml	151	
警告		未能找到引用的组件“Microsoft.Expression.Drawing”。	MrMitch.Loaders			
警告		未能找到引用的组件“Microsoft.Expression.Interactions”。	MrMitch.Loaders			
警告		未能找到引用的组件“System.Windows.Interactivity”。	MrMitch.Loaders			
警告		未能解析此引用。未能找到程序集“Microsoft.Expression.Drawing”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	MrMitch.Loaders			
警告		未能解析此引用。未能找到程序集“Microsoft.Expression.Interactions”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	MrMitch.Loaders			
警告		未能解析此引用。未能找到程序集“System.Windows.Interactivity”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	MrMitch.Loaders			
警告	CS1998	此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上执行占用大量 CPU 的工作。	OsuPlayer.Media.Audio	C:\GitHub\Osu-Player\OsuPlayer.Media.Audio\Music\MusicPlayer.cs	73	活动的
警告	CS4014	由于此调用不会等待，因此在此调用完成之前将会继续执行当前方法。请考虑将 "await" 运算符应用于调用结果。	OsuPlayer.Media.Audio	C:\GitHub\Osu-Player\OsuPlayer.Media.Audio\Music\MusicPlayer.cs	113	活动的
错误		类型引用无法找到名为“Arc”的公共类型。 行 103 位置 52.	MrMitch.Loaders	C:\GitHub\Osu-Player\MrMitch.Loaders\Themes\Generic.xaml	103	
错误		类型引用无法找到名为“Arc”的公共类型。 行 21 位置 36.	MrMitch.Loaders	C:\GitHub\Osu-Player\MrMitch.Loaders\GooglePlusLoader.xaml	21	
`

Something goes wrong with MrMitch.Loader

**Comment by Milkitic** [comment]
Microsoft Expression Blend SDK for .NET 4 was needed:
https://www.microsoft.com/en-us/download/details.aspx?id=10801
Since this is an extra SDK, I will consider to replace this library in the future.
